version: "3.8"

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "test"

  data_filler:
    build: ./DataFiller
    container_name: DataFiller
    depends_on:
      - postgres
    restart: "no"
    environment:
      - ROWS_COUNT=1000000

  sync_flask:
    build: ./SyncFlaskService
    container_name: SyncFlaskService
    depends_on:
      - data_filler
    restart: "no"
    ports:
      - "5000:5000"